
sudo: false

language: 'php'

php: '5.6'

env:
  - COMPOSER_NO_INTERACTION=1 COMPOSER_DISABLE_XDEBUG_WARN=1

cache:
  directories:
    - '$HOME/.composer/cache'

install:
  - 'composer install'

script:
  - './bin/robo lint'
  - './bin/robo test'
